name: CDN Cache Purge

on:
  push:
    paths:
      - 'public/**'
      - 'scripts/version-assets.js'
      - 'package.json'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Purge CDN Cache (Cloudflare)
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
